apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacex-api
  labels:
    app: spacex-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacex-api
  template:
    metadata:
      labels:
        app: spacex-api
    spec:
      containers:
        - name: spacex-api
          image: spacex-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5