apiVersion: v1
kind: Service
metadata:
  name: spacex-api-service
  labels:
    app: spacex-api
spec:
  type: NodePort
  selector:
    app: spacex-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
      name: http